---
- name: Server ongoing tasks
  hosts: all
  gather_facts: yes
  remote_user: "{{ (users | selectattr('name', 'equalto', 'ansible') | list | first).name }}"
  become: true
  vars:
    ansible_ssh_private_key_file: "{{ (users | selectattr('name', 'equalto', 'ansible') | list | first).key }}"
  vars_files:
    - group_vars/all/main.yaml

  roles:
    - update-packages
    - kind-install
    - kind-cluster
    - energy-saving


