# Specify the user you want to create here. The same user 
# will be created on all the hosts.
initial_user: patryk
initial_password: change-me

# SSH port
ssh_port: 22

# This tells Ansible where to find the SSH public key fingerprint file
# to copy over to the target hosts. If the name of your local machine's
# SSH public key fingerprint file is not `id_rsa.pub`, you'll have
# to change it here.
users:
  - name: pp
    # password: patryk
    key: ~/.ssh/id_ed25519.pub
  - name: ansible
    # password: ansible
    key:  ~/.ssh/id_ansible.pub

# Set energy saving shutdown cron job
energySaving:
  scheduledShutdownHour: "19"
  scheduledShutdownMinute: "0"