kind: Pod
apiVersion: v1
metadata:
  name: hello-app
  labels:
    app: hello
spec:
  containers:
  - name: hello-app
    image: hashicorp/http-echo:0.2.3
    args:
    - "-text=Welcome!"
---
kind: Service
apiVersion: v1
metadata:
  name: hello-service
spec:
  selector:
    app: hello
  ports:
  # Default port used by the image
  - port: 5678
---
kind: Pod
apiVersion: v1
metadata:
  name: ping-app
  labels:
    app: ping
spec:
  containers:
  - name: ping-app
    image: hashicorp/http-echo:0.2.3
    args:
    - "-text=pong... very funny... ha ha...."
---
kind: Service
apiVersion: v1
metadata:
  name: ping-service
spec:
  selector:
    app: ping
  ports:
  # Default port used by the image
  - port: 5678
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/hello"
        backend:
          service:
            name: hello-service
            port:
              number: 5678
      - pathType: Prefix
        path: "/ping"
        backend:
          service:
            name: ping-service
            port:
              number: 5678
---
